import imgLogo from "@/assets/images/logo.png"
import Head from 'next/head'
import React, { useReducer } from "react";
import style from "@/styles/auth.module.css";
import Image from "next/image";
import { useRouter } from "next/router";

const AuthLayout = (page, title, img) => {
    const router=useRouter();
    return (
    <>
    <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
    <div className={ style.authContainer}>
            <div className={"container-fulid " + style.auth} >
                <div className="row">
                    <div className={"col-2 " + style.logo }>
                        <Image onClick={()=>router.push('/')} src={imgLogo}  />
                    </div>    
                </div>
                <div className="container">
                    <div className="row">
                        <div className={"col-6 col-md-6 offset-1 offset-md-1 "}>
                            
                                {page}
                            
                        </div>
                        <div className={"col-5  d-flex justify-content-center "+ style.authImg}>
                            <Image src={img} alt="register-img"  />
                        </div>
                    </div>
                </div>
            </div>
        </div>
        </main>
    </>
    );
};

export default AuthLayout;
